version: "3.9"
services:
  app:
    build:
      ./infra/php
    volumes:
      - ./backend:/work

  web:
    image: nginx:stable
    ports:
      - 10080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work